### ISSUE TITLE
Mod: Witchery

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#84]
**Mod Name:** Witchery
**Author:** Emoniph
**Link:** https://sites.google.com/site/witcherymod/

**Comment by ghost** [comment]
I think this could be cool but it depends what other magic mods we are going to be putting in because I know that I will do maybe 2 magic mods at some point 1 of which will be EE3. If there are people who are actually interested in this mod great but we don't want to add mods which are going to be ignored like in the last pack

**Comment by BuilderJah** [comment]
I'll be doing EE3, AE2, and ThaumCraft 3. I might to Witchery, but it's better to add it in a later patch, because I can't be bothered starting with Witchery early-game. It's quite resource-intensive.
